    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}
          IMAGE_ID_LOWER=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
          FULL_IMAGE_NAME="${IMAGE_ID_LOWER}/rag-chatbot:latest"
          echo "Using image name: $FULL_IMAGE_NAME"
          docker build -t $FULL_IMAGE_NAME .
          docker push $FULL_IMAGE_NAME
